//
// Este archivo ha sido generado por Eclipse Implementation of JAXB v4.0.2 
// Visite https://eclipse-ee4j.github.io/jaxb-ri 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
//


package com.example.demo.wsdl.ordencompracentral;


import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.wsdl.ordencompracentral package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.wsdl.ordencompracentral
     * 
     */
    public ObjectFactory() {

    }

    /**
     * Create an instance of {@link GetOrdenCompraCentralRequest }
     * 
     * @return
     *     the new instance of {@link GetOrdenCompraCentralRequest }
     */
    public GetOrdenCompraCentralRequest createGetOrdenCompraCentralRequest() {
        return new GetOrdenCompraCentralRequest();
        
    }

    /**
     * Create an instanc// The code you provided is a Java class generated by Eclipse JAXB
     // implementation. The `@XmlRegistry` annotation is used to indicate that the
     // class is an object factory. An object factory class in JAXB is responsible
     // for creating instances of schema-derived classes for a specific package.
    {@link GetOrdenCompraResponse }
     * 
     * @return
     *     the new instance of {@link GetOrdenCompraCentralResponse }
     */
    public GetOrdenCompraCentralResponse createGetOrdenCompraCentralResponse() {
        return new GetOrdenCompraCentralResponse();
    }

    /**
     * Create an instance of {@link OrdenCompraCentral }
     * 
     * @return
     *     the new instance of {@link OrdenCompraCentral }
     */
    public OrdenCompraCentral createOrdenCompraCentral() {
        return new OrdenCompraCentral();
    }

    /**
     * Create an instance of {@link GetAllOrdenesCompraRequest }
     * 
     * @return
     *     the new instance of {@link GetAllOrdenesCompraRequest }
     */
    public GetAllOrdenesCompraCentralRequest createGetAllOrdenesCompraCentralRequest() {
        return new GetAllOrdenesCompraCentralRequest();
    }

    /**
     * Create an instance of {@link GetAllOrdenesCompraResponse }
     * 
     * @return
     *     the new instance of {@link GetAllOrdenesCompraResponse }
     */
    public GetAllOrdenesCompraCentralResponse createGetAllOrdenesCompraCentralResponse() {
        return new GetAllOrdenesCompraCentralResponse();
    }

    private static class GetAllOrdenesCompraCentralResponse {

        public GetAllOrdenesCompraCentralResponse() {
        }
    }

}
