# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcpb2 import empty_pb2 as empty__pb2
from grpcpb2 import producto_tienda_pb2 as producto__tienda__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in producto_tienda_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoTiendaServiceStub(object):
    """Servicios para ProductoTienda
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProductoTienda = channel.unary_unary(
                '/grpcpb2.ProductoTiendaService/CreateProductoTienda',
                request_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
                response_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                _registered_method=True)
        self.GetProductoTienda = channel.unary_unary(
                '/grpcpb2.ProductoTiendaService/GetProductoTienda',
                request_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
                response_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                _registered_method=True)
        self.UpdateProductoTienda = channel.unary_unary(
                '/grpcpb2.ProductoTiendaService/UpdateProductoTienda',
                request_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
                response_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                _registered_method=True)
        self.DeleteProductoTienda = channel.unary_unary(
                '/grpcpb2.ProductoTiendaService/DeleteProductoTienda',
                request_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
                response_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                _registered_method=True)
        self.ListProductoTiendas = channel.unary_unary(
                '/grpcpb2.ProductoTiendaService/ListProductoTiendas',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=producto__tienda__pb2.ProductoTiendaList.FromString,
                _registered_method=True)


class ProductoTiendaServiceServicer(object):
    """Servicios para ProductoTienda
    """

    def CreateProductoTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductoTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductoTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProductoTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProductoTiendas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoTiendaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProductoTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProductoTienda,
                    request_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                    response_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
            ),
            'GetProductoTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductoTienda,
                    request_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                    response_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
            ),
            'UpdateProductoTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductoTienda,
                    request_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                    response_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
            ),
            'DeleteProductoTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProductoTienda,
                    request_deserializer=producto__tienda__pb2.ProductoTienda.FromString,
                    response_serializer=producto__tienda__pb2.ProductoTienda.SerializeToString,
            ),
            'ListProductoTiendas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProductoTiendas,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=producto__tienda__pb2.ProductoTiendaList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcpb2.ProductoTiendaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcpb2.ProductoTiendaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoTiendaService(object):
    """Servicios para ProductoTienda
    """

    @staticmethod
    def CreateProductoTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoTiendaService/CreateProductoTienda',
            producto__tienda__pb2.ProductoTienda.SerializeToString,
            producto__tienda__pb2.ProductoTienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductoTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoTiendaService/GetProductoTienda',
            producto__tienda__pb2.ProductoTienda.SerializeToString,
            producto__tienda__pb2.ProductoTienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductoTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoTiendaService/UpdateProductoTienda',
            producto__tienda__pb2.ProductoTienda.SerializeToString,
            producto__tienda__pb2.ProductoTienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProductoTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoTiendaService/DeleteProductoTienda',
            producto__tienda__pb2.ProductoTienda.SerializeToString,
            producto__tienda__pb2.ProductoTienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProductoTiendas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoTiendaService/ListProductoTiendas',
            empty__pb2.Empty.SerializeToString,
            producto__tienda__pb2.ProductoTiendaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
