# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpcpb2 import empty_pb2 as empty__pb2
from grpcpb2 import producto_pb2 as producto__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in producto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoServiceStub(object):
    """Servicios para Producto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducto = channel.unary_unary(
                '/grpcpb2.ProductoService/CreateProducto',
                request_serializer=producto__pb2.Producto.SerializeToString,
                response_deserializer=producto__pb2.Producto.FromString,
                _registered_method=True)
        self.GetProducto = channel.unary_unary(
                '/grpcpb2.ProductoService/GetProducto',
                request_serializer=producto__pb2.Producto.SerializeToString,
                response_deserializer=producto__pb2.Producto.FromString,
                _registered_method=True)
        self.UpdateProducto = channel.unary_unary(
                '/grpcpb2.ProductoService/UpdateProducto',
                request_serializer=producto__pb2.Producto.SerializeToString,
                response_deserializer=producto__pb2.Producto.FromString,
                _registered_method=True)
        self.DeleteProducto = channel.unary_unary(
                '/grpcpb2.ProductoService/DeleteProducto',
                request_serializer=producto__pb2.Producto.SerializeToString,
                response_deserializer=producto__pb2.Producto.FromString,
                _registered_method=True)
        self.ListProductos = channel.unary_unary(
                '/grpcpb2.ProductoService/ListProductos',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=producto__pb2.ProductoList.FromString,
                _registered_method=True)


class ProductoServiceServicer(object):
    """Servicios para Producto
    """

    def CreateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducto,
                    request_deserializer=producto__pb2.Producto.FromString,
                    response_serializer=producto__pb2.Producto.SerializeToString,
            ),
            'GetProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducto,
                    request_deserializer=producto__pb2.Producto.FromString,
                    response_serializer=producto__pb2.Producto.SerializeToString,
            ),
            'UpdateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProducto,
                    request_deserializer=producto__pb2.Producto.FromString,
                    response_serializer=producto__pb2.Producto.SerializeToString,
            ),
            'DeleteProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProducto,
                    request_deserializer=producto__pb2.Producto.FromString,
                    response_serializer=producto__pb2.Producto.SerializeToString,
            ),
            'ListProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProductos,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=producto__pb2.ProductoList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcpb2.ProductoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpcpb2.ProductoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoService(object):
    """Servicios para Producto
    """

    @staticmethod
    def CreateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoService/CreateProducto',
            producto__pb2.Producto.SerializeToString,
            producto__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoService/GetProducto',
            producto__pb2.Producto.SerializeToString,
            producto__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoService/UpdateProducto',
            producto__pb2.Producto.SerializeToString,
            producto__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoService/DeleteProducto',
            producto__pb2.Producto.SerializeToString,
            producto__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpcpb2.ProductoService/ListProductos',
            empty__pb2.Empty.SerializeToString,
            producto__pb2.ProductoList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
