# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: producto_tienda.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'producto_tienda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15producto_tienda.proto\x1a\x0b\x65mpty.proto\"t\n\x0eProductoTienda\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0bproducto_id\x18\x02 \x01(\x03\x12\x11\n\ttienda_id\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\x12\r\n\x05talle\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x06 \x01(\x05\"8\n\x12ProductoTiendaList\x12\"\n\tproductos\x18\x01 \x03(\x0b\x32\x0f.ProductoTienda2\xb0\x02\n\x15ProductoTiendaService\x12\x38\n\x14\x43reateProductoTienda\x12\x0f.ProductoTienda\x1a\x0f.ProductoTienda\x12\x35\n\x11GetProductoTienda\x12\x0f.ProductoTienda\x1a\x0f.ProductoTienda\x12\x38\n\x14UpdateProductoTienda\x12\x0f.ProductoTienda\x1a\x0f.ProductoTienda\x12\x38\n\x14\x44\x65leteProductoTienda\x12\x0f.ProductoTienda\x1a\x0f.ProductoTienda\x12\x32\n\x13ListProductoTiendas\x12\x06.Empty\x1a\x13.ProductoTiendaListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producto_tienda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOTIENDA']._serialized_start=38
  _globals['_PRODUCTOTIENDA']._serialized_end=154
  _globals['_PRODUCTOTIENDALIST']._serialized_start=156
  _globals['_PRODUCTOTIENDALIST']._serialized_end=212
  _globals['_PRODUCTOTIENDASERVICE']._serialized_start=215
  _globals['_PRODUCTOTIENDASERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
