# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tienda.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tienda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctienda.proto\x1a\x0b\x65mpty.proto\"x\n\x06Tienda\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x11\n\tdireccion\x18\x02 \x01(\t\x12\x0e\n\x06\x63iudad\x18\x03 \x01(\t\x12\x11\n\tprovincia\x18\x04 \x01(\t\x12\x12\n\nhabilitada\x18\x05 \x01(\x08\x12\x14\n\x0cproducto_ids\x18\x06 \x03(\x03\"&\n\nTiendaList\x12\x18\n\x07tiendas\x18\x01 \x03(\x0b\x32\x07.Tienda2\xb8\x01\n\rTiendaService\x12 \n\x0c\x43reateTienda\x12\x07.Tienda\x1a\x07.Tienda\x12\x1d\n\tGetTienda\x12\x07.Tienda\x1a\x07.Tienda\x12 \n\x0cUpdateTienda\x12\x07.Tienda\x1a\x07.Tienda\x12 \n\x0c\x44\x65leteTienda\x12\x07.Tienda\x1a\x07.Tienda\x12\"\n\x0bListTiendas\x12\x06.Empty\x1a\x0b.TiendaListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tienda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIENDA']._serialized_start=29
  _globals['_TIENDA']._serialized_end=149
  _globals['_TIENDALIST']._serialized_start=151
  _globals['_TIENDALIST']._serialized_end=189
  _globals['_TIENDASERVICE']._serialized_start=192
  _globals['_TIENDASERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
