# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import empty_pb2 as empty__pb2
import tienda_pb2 as tienda__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tienda_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TiendaServiceStub(object):
    """Servicios para Tienda
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTienda = channel.unary_unary(
                '/TiendaService/CreateTienda',
                request_serializer=tienda__pb2.Tienda.SerializeToString,
                response_deserializer=tienda__pb2.Tienda.FromString,
                _registered_method=True)
        self.GetTienda = channel.unary_unary(
                '/TiendaService/GetTienda',
                request_serializer=tienda__pb2.Tienda.SerializeToString,
                response_deserializer=tienda__pb2.Tienda.FromString,
                _registered_method=True)
        self.UpdateTienda = channel.unary_unary(
                '/TiendaService/UpdateTienda',
                request_serializer=tienda__pb2.Tienda.SerializeToString,
                response_deserializer=tienda__pb2.Tienda.FromString,
                _registered_method=True)
        self.DeleteTienda = channel.unary_unary(
                '/TiendaService/DeleteTienda',
                request_serializer=tienda__pb2.Tienda.SerializeToString,
                response_deserializer=tienda__pb2.Tienda.FromString,
                _registered_method=True)
        self.ListTiendas = channel.unary_unary(
                '/TiendaService/ListTiendas',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=tienda__pb2.TiendaList.FromString,
                _registered_method=True)


class TiendaServiceServicer(object):
    """Servicios para Tienda
    """

    def CreateTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTiendas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TiendaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTienda,
                    request_deserializer=tienda__pb2.Tienda.FromString,
                    response_serializer=tienda__pb2.Tienda.SerializeToString,
            ),
            'GetTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTienda,
                    request_deserializer=tienda__pb2.Tienda.FromString,
                    response_serializer=tienda__pb2.Tienda.SerializeToString,
            ),
            'UpdateTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTienda,
                    request_deserializer=tienda__pb2.Tienda.FromString,
                    response_serializer=tienda__pb2.Tienda.SerializeToString,
            ),
            'DeleteTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTienda,
                    request_deserializer=tienda__pb2.Tienda.FromString,
                    response_serializer=tienda__pb2.Tienda.SerializeToString,
            ),
            'ListTiendas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTiendas,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=tienda__pb2.TiendaList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TiendaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TiendaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TiendaService(object):
    """Servicios para Tienda
    """

    @staticmethod
    def CreateTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TiendaService/CreateTienda',
            tienda__pb2.Tienda.SerializeToString,
            tienda__pb2.Tienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TiendaService/GetTienda',
            tienda__pb2.Tienda.SerializeToString,
            tienda__pb2.Tienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TiendaService/UpdateTienda',
            tienda__pb2.Tienda.SerializeToString,
            tienda__pb2.Tienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TiendaService/DeleteTienda',
            tienda__pb2.Tienda.SerializeToString,
            tienda__pb2.Tienda.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTiendas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TiendaService/ListTiendas',
            empty__pb2.Empty.SerializeToString,
            tienda__pb2.TiendaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
